stages:
  - test
  - analyze

image: $CI_REGISTRY/alphabill/gitlab-ci-image:main

include:
  - project: "$CI_PROJECT_NAMESPACE/gitlab-ci-image"
    file:
      - "/templates/go-cache.gitlab-ci.yml"
      - "/templates/go-vet.gitlab-ci.yml"
      - "/templates/gosec.gitlab-ci.yml"
      # TODO: Enable nancy - "/templates/nancy.gitlab-ci.yml"
      - "/templates/sonarqube.gitlab-ci.yml"
      - "/templates/trivy.gitlab-ci.yml"

vet:
  stage: test
  extends:
    - .go-cache
  needs: []
  script:
    - go vet ./...

test:
  stage: test
  extends:
    - .go-cache
  needs:
    # tests are expensive compared to vet so do not start tests unless vet job succeeded
    - vet
  script:
    - gotestsum --junitfile report.xml --format standard-quiet -- ./... -race -count=1 -coverprofile test-coverage.out
    - go tool cover -func test-coverage.out
    - gocover-cobertura < test-coverage.out > test-coverage-cobertura.xml
  coverage: '/\(statements\)(?:\s+)?(\d+(?:\.\d+)?%)/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: test-coverage-cobertura.xml
      junit: report.xml
    paths:
      - test-coverage.out
    when: always

sonarqube-check:
  needs: ["gosec", "test"]
